context('group')

test_that("groupSmoothedMean() returns consistent results", {
  dt <- groupSmoothedMean(data.xy, 'x', 'y')
  expect_equal_to_reference(dt,"loess.rds")
  dt <- groupSmoothedMean(data.xy, 'x', 'y','group')
  expect_equal_to_reference(dt,"loess.group.rds")
  dt <- groupSmoothedMean(data.xy, 'x', 'y', NULL, 'panel')
  expect_equal_to_reference(dt,"loess.panel.rds")
  dt <- groupSmoothedMean(data.xy, 'x', 'y', 'group', 'panel')
  expect_equal_to_reference(dt,"loess.group.panel.rds")
  dt <- groupSmoothedMean(bigData.xy, 'x', 'y')
  expect_equal_to_reference(dt,"gam.rds")
  dt <- groupSmoothedMean(bigData.xy, 'x', 'y','group')
  expect_equal_to_reference(dt,"gam.group.rds")
  dt <- groupSmoothedMean(bigData.xy, 'x', 'y', NULL, 'panel')
  expect_equal_to_reference(dt,"gam.panel.rds")
  dt <- groupSmoothedMean(bigData.xy, 'x', 'y', 'group', 'panel')
  expect_equal_to_reference(dt,"gam.group.panel.rds")
})

test_that("groupDensity() returns consistent results", {
  dt <- groupDensity(data.binned,'y')
  expect_equal_to_reference(dt,"density.rds")
  dt <- groupDensity(data.binned, 'y','group')
  expect_equal_to_reference(dt,"density.group.rds")
  dt <- groupDensity(data.binned, 'y', NULL, 'panel')
  expect_equal_to_reference(dt,"density.panel.rds")
  dt <- groupDensity(data.binned, 'y', 'group', 'panel')
  expect_equal_to_reference(dt,"density.group.panel.rds")
})
