context('mosaic')

test_that("mosaic.dt() returns an appropriately sized data.table", {
  map <- data.frame('id' = c('group', 'var', 'panel'), 'plotRef' = c('yAxisVariable', 'xAxisVariable', 'facetVariable1'), 'dataType' = c('STRING', 'STRING', 'STRING'), 'dataShape' = c('CATEGORICAL', 'CATEGORICAL', 'CATEGORICAL'), stringsAsFactors=FALSE)

  dt <- mosaic.dt(data.binary, map)
  expect_is(dt, 'data.table')
  expect_is(dt, 'mosaic')
  expect_is(dt$value, 'list')
  expect_is(dt$value[[1]], 'list')
  expect_equal(nrow(dt),4)
  expect_equal(names(dt),c('xLabel', 'yLabel', 'value', 'panel'))
  expect_equal(dt$xLabel[[1]],c('var1','var2'))
  expect_equal(dt$yLabel[[1]],c('group1','group2'))
  expect_equal(length(dt$value[[1]]),2)
  expect_equal(length(dt$value[[1]][[1]]),2)
  statsTable <- statsTable(dt)
  expect_equal(names(statsTable), c(c('oddsratio', 'relativerisk', 'orInterval', 'rrInterval', 'pvalue', 'panel')))
  sampleSizeTable <- sampleSizeTable(dt)
  expect_equal(names(sampleSizeTable),c('panel','var','size'))
  expect_equal(class(sampleSizeTable$var[[1]]), 'character')

  map <- data.frame('id' = c('group', 'var'), 'plotRef' = c('yAxisVariable', 'xAxisVariable'), 'dataType' = c('STRING', 'STRING'), 'dataShape' = c('CATEGORICAL', 'CATEGORICAL'), stringsAsFactors=FALSE)

  dt <- mosaic.dt(data.binary, map)
  expect_is(dt, 'data.table')
  expect_is(dt, 'mosaic')
  expect_is(dt$value, 'list')
  expect_is(dt$value[[1]], 'list')
  expect_equal(nrow(dt),1)
  expect_equal(names(dt),c('xLabel', 'yLabel', 'value'))
  statsTable <- statsTable(dt)
  expect_equal(names(statsTable), c(c('oddsratio', 'relativerisk', 'orInterval', 'rrInterval', 'pvalue')))
})

test_that("mosaic() returns appropriately formatted json", {
  map <- data.frame('id' = c('group', 'var', 'panel'), 'plotRef' = c('yAxisVariable', 'xAxisVariable', 'facetVariable1'), 'dataType' = c('STRING', 'STRING', 'STRING'), 'dataShape' = c('CATEGORICAL', 'CATEGORICAL', 'CATEGORICAL'), stringsAsFactors=FALSE)
  dt <- mosaic.dt(data.binary, map)
  outJson <- getJSON(dt)
  jsonList <- jsonlite::fromJSON(outJson)

  expect_equal(names(jsonList),c('mosaic','sampleSizeTable','statsTable'))
  expect_equal(names(jsonList$mosaic),c('data','config'))
  expect_equal(names(jsonList$mosaic$data),c('xLabel','yLabel','value','facetVariableDetails'))
  expect_equal(names(jsonList$mosaic$data$facetVariableDetails),c('variableId','entityId','value'))
  expect_equal(nrow(jsonList$mosaic$data$facetVariableDetails), 4)
  expect_equal(names(jsonList$mosaic$config),c('incompleteCases','xVariableDetails','yVariableDetails'))
  expect_equal(names(jsonList$mosaic$config$xVariableDetails),c('variableId','entityId'))
  expect_equal(names(jsonList$sampleSizeTable),c('facetVariableDetails','xVariableDetails','size'))
  expect_equal(names(jsonList$statsTable),c('oddsratio','relativerisk','orInterval','rrInterval','pvalue','facetVariableDetails'))
})
